name: tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_0
  - beautifulsoup4=4.8.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.7=py37ha12b0ac_0
  - fuzzywuzzy=0.17.0=py_0
  - idna=2.8=py37_0
  - intel-openmp=2019.4=233
  - joblib=0.13.2=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - llvm-openmp=4.0.1=hcfea43d_1
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.14=py37h5e564d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.16.5=py37hacdab7b_0
  - numpy-base=1.16.5=py37h6575580_0
  - openssl=1.1.1d=h1de35cc_1
  - pandas=0.25.1=py37h0a44026_0
  - pip=19.2.2=py37_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.0.0=py37_0
  - pysocks=1.7.0=py37_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.0=py37_0
  - python-levenshtein=0.12.0=py37h01d97ff_1001
  - pytz=2019.2=py_0
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py37_0
  - scikit-learn=0.21.2=py37h27c97d8_0
  - scipy=1.3.1=py37h1410ff5_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - soupsieve=1.9.2=py37_0
  - sqlite=3.29.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - urllib3=1.24.2=py37_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/ryandavis/anaconda3/envs/tutorials

